#!/usr/bin/env bash
# wallpaper.sh — set the desktop background (idempotent; per-monitor aware).
#
# Reads ~/.config/hypr/generated/wallpapers.conf, written atomically by
# Settings → Wallpaper:
#     mode=fill|fit|stretch|tile|center
#     *=/path/to/default.jpg          # every output without its own line
#     DP-1=/path/to/that-monitor.jpg  # per-output override
#
# Backend preference: swww (animated) → hyprpaper → swaybg (the one hypr-shell
# ships). `--reapply` re-asserts the config — Settings calls it after a change,
# HyprMon on monitor hotplug, so a newly plugged display gets its wallpaper.
# Legacy fallback (no conf): $DE_WALLPAPER, then ~/.config/hypr/wallpaper.{jpg,…}.

set -u

REAPPLY=0
[ "${1:-}" = "--reapply" ] && REAPPLY=1

CONF="$HOME/.config/hypr/generated/wallpapers.conf"
MODE=fill
DEFAULT=""
declare -A PER=()

if [ -r "$CONF" ]; then
    while IFS='=' read -r k v; do
        case "$k" in
            ''|\#*) ;;
            mode) MODE="$v" ;;
            \*) DEFAULT="$v" ;;
            *) [ -n "$v" ] && PER["$k"]="$v" ;;
        esac
    done < "$CONF"
fi

# legacy single-image fallback when no conf exists yet
if [ -z "$DEFAULT" ] && [ "${#PER[@]}" -eq 0 ]; then
    for f in \
        "${DE_WALLPAPER:-}" \
        "$HOME/.config/hypr/wallpaper.jpg" \
        "$HOME/.config/hypr/wallpaper.jpeg" \
        "$HOME/.config/hypr/wallpaper.png"
    do
        if [ -n "$f" ] && [ -r "$f" ]; then DEFAULT="$f"; break; fi
    done
fi

# ── swww ──────────────────────────────────────────────────────────────────────
if command -v swww >/dev/null 2>&1; then
    pgrep -x swww-daemon >/dev/null 2>&1 || { swww-daemon >/dev/null 2>&1 & sleep 0.4; }
    case "$MODE" in fit) RS=fit ;; *) RS=crop ;; esac
    [ -n "$DEFAULT" ] && swww img "$DEFAULT" --resize "$RS" >/dev/null 2>&1
    for o in "${!PER[@]}"; do swww img "${PER[$o]}" -o "$o" --resize "$RS" >/dev/null 2>&1; done
    exit 0
fi

# ── hyprpaper ─────────────────────────────────────────────────────────────────
if command -v hyprpaper >/dev/null 2>&1; then
    HPC="$HOME/.config/hypr/hyprpaper.conf"
    {
        echo "# AUTO-GENERATED by wallpaper.sh — edit wallpapers.conf instead"
        [ -n "$DEFAULT" ] && { echo "preload = $DEFAULT"; echo "wallpaper = ,$DEFAULT"; }
        for o in "${!PER[@]}"; do echo "preload = ${PER[$o]}"; echo "wallpaper = $o,${PER[$o]}"; done
        echo "splash = false"
    } > "$HPC"
    if [ "$REAPPLY" -eq 1 ]; then pkill -x hyprpaper 2>/dev/null; sleep 0.2; fi
    pgrep -x hyprpaper >/dev/null 2>&1 || hyprpaper >/dev/null 2>&1 &
    exit 0
fi

# ── swaybg (shipped default) ──────────────────────────────────────────────────
command -v swaybg >/dev/null 2>&1 || exit 0
if [ "$REAPPLY" -eq 0 ] && pgrep -x swaybg >/dev/null 2>&1; then exit 0; fi

args=()
[ -n "$DEFAULT" ] && args+=(-i "$DEFAULT" -m "$MODE")
for o in "${!PER[@]}"; do args+=(-o "$o" -i "${PER[$o]}" -m "$MODE"); done
# no image at all → solid Gruvbox background so the root is never garbage
[ "${#args[@]}" -eq 0 ] && args=(-c "#282828")

pkill -x swaybg 2>/dev/null
exec swaybg "${args[@]}" >/dev/null 2>&1
