#!/usr/bin/env bash
# helium-theme.sh <flock|blacksheep> <accent-hex6> — theme Helium (the DE's
# browser) to match ewe. Called by colorscheme.sh, so it follows Settings →
# Theme live: surface style + accent in, browser chrome out.
#
# Two write targets:
#   1. ~/.config/helium-browser-flags.conf — the wrapper reads it on every
#      launch; --install-autogenerated-theme re-derives the whole Chromium
#      theme from our surface colour each start (idempotent, follows theme
#      switches without touching the profile while the browser runs).
#   2. every profile's Preferences (+ a pre-seeded Default for first run):
#      helium.browser.layout (vertical tabs — ewe's default; override with
#      `ewe-conf set desktop.browser.layout '"horizontal"'`, synced like
#      everything else in the one file) — skipped while Helium is running
#      (Chromium rewrites Preferences on exit and would clobber the edit).
set -u

STYLE="${1:-flock}"
ACC="${2:-ff9f0a}"; ACC="${ACC#\#}"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
HDIR="$CFG/net.imput.helium"

# surface colour per style — same values Theme.qml uses
case "$STYLE" in
    blacksheep) S_HEX="020202" ;;
    *)          S_HEX="1c1c1e" ;;
esac
R=$((16#${S_HEX:0:2})); G=$((16#${S_HEX:2:2})); B=$((16#${S_HEX:4:2}))

# 1 · flags: theme from the surface colour + quiet defaults
cat > "$CFG/helium-browser-flags.conf" <<EOF
# Generated by ewe (helium-theme.sh) — regenerated on every theme change.
# Edit desktop.browser.* in ewe.conf instead of this file.
--install-autogenerated-theme=$R,$G,$B
EOF

# 2 · vertical tabs + taste prefs into the profiles (browser must be closed)
layout="vertical"
for eweconf in "$(dirname "$0")/../../../bin/ewe-conf" "$HOME/.local/share/ewe/bin/ewe-conf" /usr/bin/ewe-conf; do
    if [ -x "$eweconf" ] || command -v "$(basename "$eweconf")" >/dev/null 2>&1; then
        v="$("$eweconf" get desktop.browser.layout 2>/dev/null || true)"
        [ -n "$v" ] && layout="$v"
        break
    fi
done

# Running check against the BINARY path — helium's processes are comm-named
# plain "chrome" and their cmdline does not carry the profile dir, so match
# /opt/helium-browser-bin/chrome (pattern split so this script's own cmdline
# never matches itself — the pkill-self-kill lesson, again).
pat="$(printf '/opt/helium-browser-bin/chrom')e"
if pgrep -f "$pat" >/dev/null 2>&1; then
    exit 0   # browser open — prefs would be clobbered on exit; flags applied anyway
fi

python3 - "$HDIR" "$layout" <<'PY' 2>/dev/null || true
import json, os, sys, glob
hdir, layout = sys.argv[1], sys.argv[2]
want_vertical = layout != "horizontal"
targets = glob.glob(os.path.join(hdir, "*", "Preferences"))
if not targets:
    # pre-seed for the very first launch
    d = os.path.join(hdir, "Default")
    os.makedirs(d, exist_ok=True)
    targets = [os.path.join(d, "Preferences")]
for t in targets:
    if "System Profile" in t:
        continue
    try:
        p = json.load(open(t))
    except (OSError, ValueError):
        p = {}
    h = p.setdefault("helium", {}).setdefault("browser", {})
    # HeliumLayoutType: 0 classic · 1 compact · 2 vertical · 3 dynamic
    h["layout"] = 2 if want_vertical else 0
    h["show_vertical_tabs_collapse_button"] = True
    tmp = t + ".ewe-tmp"
    with open(tmp, "w") as f:
        json.dump(p, f, separators=(",", ":"))
    os.replace(tmp, t)
PY
exit 0
