#!/usr/bin/env bash
# helium-theme.sh <flock|blacksheep> <accent-hex6> — dress Helium (the DE's
# browser) as a part of ewe. Called from colorscheme.sh on every theme change.
#
# What it builds (all regenerable state under ~/.local/state/ewe/helium):
#   theme/  — a real Chromium theme extension with ewe's exact surface palette
#             (the autogenerated-theme flag was tried first and produced a
#             purplish mess — Chromium invents tints; we don't let it)
#   ntp/    — a new-tab-page override extension: ewe logo centred on the
#             surface, one launcher-style search pill (DuckDuckGo)
# Both load through ~/.config/helium-browser-flags.conf (--load-extension).
#
# Preferences (per profile, only while Helium is CLOSED — Chromium rewrites
# the file on exit and would clobber us):
#   helium.browser.layout = 2      vertical tabs (HeliumLayoutType::kVertical);
#                                  override: ewe-conf set desktop.browser.layout
#                                  '"horizontal"' — synced in the one file
#   default search → DuckDuckGo    only when the current engine is a
#                                  prepopulated default (never over a custom
#                                  engine the user chose deliberately)
#   extensions.theme removed       so the old autogenerated theme lets go
set -u

STYLE="${1:-flock}"
ACC="${2:-ff9f0a}"; ACC="${ACC#\#}"
CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/ewe/helium"
HDIR="$CFG/net.imput.helium"

case "$STYLE" in
    blacksheep) BG="020202"; TOOL="101012"; ELEV="1a1a1c" ;;
    *)          BG="1c1c1e"; TOOL="2c2c2e"; ELEV="3a3a3c" ;;
esac
FG="f2f2f7"; DIM="8e8e93"
rgb() { printf '[%d, %d, %d]' $((16#${1:0:2})) $((16#${1:2:2})) $((16#${1:4:2})); }

mkdir -p "$STATE/theme" "$STATE/ntp"

# ── 1 · the theme extension ──────────────────────────────────────────────────
cat > "$STATE/theme/manifest.json" <<EOF
{
  "manifest_version": 3,
  "name": "ewe $STYLE",
  "version": "1.0",
  "description": "Generated by ewe (helium-theme.sh) — do not edit.",
  "theme": {
    "colors": {
      "frame": $(rgb "$BG"),
      "frame_inactive": $(rgb "$BG"),
      "toolbar": $(rgb "$TOOL"),
      "tab_text": $(rgb "$FG"),
      "tab_background_text": $(rgb "$DIM"),
      "bookmark_text": $(rgb "$FG"),
      "toolbar_button_icon": $(rgb "$FG"),
      "ntp_background": $(rgb "$BG"),
      "ntp_text": $(rgb "$FG"),
      "omnibox_background": $(rgb "$BG"),
      "omnibox_text": $(rgb "$FG")
    }
  }
}
EOF

# ── 2 · the new-tab page ─────────────────────────────────────────────────────
LOGO=""
for cand in "$(dirname "$0")/../assets/logo.png" "$HOME/.config/quickshell/assets/logo.png"; do
    [ -r "$cand" ] && { LOGO="$cand"; break; }
done
[ -n "$LOGO" ] && cp -f "$LOGO" "$STATE/ntp/logo.png" 2>/dev/null

cat > "$STATE/ntp/manifest.json" <<EOF
{
  "manifest_version": 3,
  "name": "ewe new tab",
  "version": "1.0",
  "description": "Generated by ewe (helium-theme.sh) — do not edit.",
  "chrome_url_overrides": { "newtab": "ntp.html" }
}
EOF

cat > "$STATE/ntp/ntp.html" <<EOF
<!doctype html><html><head><meta charset="utf-8"><title>New Tab</title><style>
  html, body { margin: 0; height: 100%; background: #$BG; }
  body { display: flex; align-items: center; justify-content: center;
         font-family: Ubuntu, sans-serif; }
  .wrap { display: flex; flex-direction: column; align-items: center; gap: 34px;
          transform: translateY(-6vh); }
  img { width: 190px; height: 190px; object-fit: contain; opacity: .92;
        -webkit-user-drag: none; user-select: none; }
  form { margin: 0; }
  input {
    width: min(560px, 78vw); box-sizing: border-box;
    padding: 15px 24px; font-size: 15px; font-family: inherit;
    color: #$FG; background: #$TOOL;
    border: 1px solid #$ELEV; border-radius: 18px; outline: none;
    caret-color: #$ACC;
  }
  input:focus { border-color: #$ACC; }
  input::placeholder { color: #$DIM; }
</style></head><body>
  <div class="wrap">
    <img src="logo.png" alt="">
    <form action="https://duckduckgo.com/" method="get">
      <input name="q" type="text" placeholder="Search the web…" autofocus autocomplete="off">
    </form>
  </div>
</body></html>
EOF

# ── 3 · flags: load both extensions on every start ───────────────────────────
cat > "$CFG/helium-browser-flags.conf" <<EOF
# Generated by ewe (helium-theme.sh) — regenerated on every theme change.
# Edit desktop.browser.* in ewe.conf instead of this file.
--load-extension=$STATE/theme,$STATE/ntp
EOF

# ── 4 · profile preferences (only while the browser is closed) ───────────────
layout="vertical"
for eweconf in "$(dirname "$0")/../../../bin/ewe-conf" "$HOME/.local/share/ewe/bin/ewe-conf" /usr/bin/ewe-conf; do
    if [ -x "$eweconf" ]; then
        v="$("$eweconf" get desktop.browser.layout 2>/dev/null || true)"
        [ -n "$v" ] && layout="$v"
        break
    fi
done

# helium's binary is /opt/helium-browser-bin/helium (NOT "chrome" — a chrome-
# pattern once left a ghost instance alive through three kill attempts) and
# its cmdline carries no profile dir — match the /opt DIRECTORY path, split
# so this script's own cmdline never matches itself (the pkill-self-kill lesson)
pat="$(printf '/opt/helium-browser-bi')n/"
if pgrep -f "$pat" >/dev/null 2>&1; then
    exit 0
fi

python3 - "$HDIR" "$layout" <<'PY' 2>/dev/null || true
import json, os, sys, glob
hdir, layout = sys.argv[1], sys.argv[2]
targets = glob.glob(os.path.join(hdir, "*", "Preferences"))
if not targets:
    d = os.path.join(hdir, "Default")
    os.makedirs(d, exist_ok=True)
    targets = [os.path.join(d, "Preferences")]
DDG = {
    "short_name": "DuckDuckGo", "keyword": "duckduckgo.com",
    "url": "https://duckduckgo.com/?q={searchTerms}",
    "suggestions_url": "https://duckduckgo.com/ac/?q={searchTerms}&type=list",
    "favicon_url": "https://duckduckgo.com/favicon.ico",
    "new_tab_url": "", "prepopulate_id": 92, "safe_for_autoreplace": True,
}
for t in targets:
    if "System Profile" in t:
        continue
    try:
        p = json.load(open(t))
    except (OSError, ValueError):
        p = {}
    h = p.setdefault("helium", {}).setdefault("browser", {})
    # HeliumLayoutType: 0 classic · 1 compact · 2 vertical · 3 dynamic
    h["layout"] = 2 if layout != "horizontal" else 0
    h["show_vertical_tabs_collapse_button"] = True
    # search: replace only a prepopulated default (Google fell in as the
    # Chromium fallback), never an engine the user configured by hand
    dsp = p.setdefault("default_search_provider_data", {})
    cur = dsp.get("mirrored_template_url_data") or {}
    if not cur or cur.get("safe_for_autoreplace") or cur.get("prepopulate_id") == 1:
        merged = dict(cur)
        merged.update(DDG)
        dsp["mirrored_template_url_data"] = merged
    # drop the old autogenerated theme so the loaded ewe theme takes over
    p.get("extensions", {}).pop("theme", None)
    tmp = t + ".ewe-tmp"
    with open(tmp, "w") as f:
        json.dump(p, f, separators=(",", ":"))
    os.replace(tmp, t)
PY
exit 0
